# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1840e9d5ea4737d26557512b275bfea9e6eee7088401c52d1a154852b31fa9d62b0dd6b34523d2ed6527ccf0e5ee1a8902170d080ef7beee35cdb89fcf1ddd8a

test:
  secret_key_base: bb8f0031cfa348ae13f911a59318eaff46c0a83e9be83fe43527b705a615829bc67fd10a6c377378fa21d64a6fa52033acfb3c87f7ba49bbf9854b95b5c9fccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
